services:
  bio-db:
    build: bio_db
    container_name: bio_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./bio_db/init:/docker-entrypoint-initdb.d

  bio-worker:
    build: bio_worker
    container_name: bio_worker
    depends_on:
      - bio-db
    environment:
      PYTHONPATH: /app
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      EMAIL: ${EMAIL}