services:
  bio-db:
    build: ./bio-db
    container_name: bio-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./bio-db/init:/docker-entrypoint-initdb.d

  bio-worker:
    build: ./bio-worker
    container_name: bio-worker
    depends_on:
      - bio-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      EMAIL: ${EMAIL}