services:
  bio-db:
    build: bio_db
    container_name: bio_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./bio_db/init:/docker-entrypoint-initdb.d

  bio-worker:
    build:
      context: ./bio_worker
    container_name: bio_worker
    depends_on:
      - bio-db
    volumes:
      - ./bio_worker:/app
    environment:
      PYTHONPATH: /app
      DB_HOST: ${WORKER_DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${WORKER_DB_USER}
      DB_PASS: ${WORKER_DB_PASS}
      EMAIL: ${EMAIL}