[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[flake8]
max-line-length = 79
exclude = ".git,__pycache__,build,dist"